tap "heroku/brew"
tap "stripe/stripe-cli"

brew "fzf"
brew "gh"
brew "git-extras"
brew "heroku/brew/heroku"
brew "rbenv"
brew "ruby-build"
brew "stripe/stripe-cli/stripe"
brew "the_silver_searcher"
brew "vim"
brew "balena-cli"

cask "1password"
cask "aws-vault"
cask "dash"
cask "docker"
cask "google-chrome"
cask "hammerspoon"
cask "imageoptim"
cask "keybase"
cask "notion"
cask "postgres-unofficial"
cask "slack"
cask "spotify"
cask "steam"
cask "tuple"
