tap "heroku/brew"
tap "stripe/stripe-cli"

brew "balena-cli"
brew "fzf"
brew "gh"
brew "git-extras"
brew "heroku/brew/heroku"
brew "ripgrep"
brew "rust"
brew "stow"
brew "stripe/stripe-cli/stripe"
brew "vim"
brew "mise"

cask "1password"
cask "aws-vault"
cask "dash"
cask "docker"
cask "google-chrome"
cask "imageoptim"
cask "notion"
cask "postgres-unofficial"
cask "rectangle"
cask "slack"
cask "spotify"
cask "steam"
cask "tuple"
