#!/usr/bin/env bash

#####
# Usage
#
# `./install`
#
# -u    Do a `git pull`, `git push` & `git submodule update` before installing
#####

CURRENT_DIR=`pwd`
DOTFILES="$CURRENT_DIR/.*"
VIM_DIR="$CURRENT_DIR/.vim"
GIT_UPDATE=false
FIRST_RUN=false

if [[ "$1" == "-u" ]]; then
  GIT_UPDATE=true
fi

if [[ ! -d "$CURRENT_DIR/.git/modules/.vim/bundle/vundle"]]; then
  FIRST_RUN=true
fi

if $GIT_UPDATE || $FIRST_RUN; then
  echo 'Updating git repo...'
  git pull --rebase origin master
  git push origin master

  echo 'Updating git submodules...'
  git submodule init
  git submodule update
fi

ln -sfv $VIM_DIR ~

for dotfile in $DOTFILES; do
  if [[ ! "$dotfile" =~ \.git(ignore|modules)$ ]] && [[ -f "$dotfile" ]]; then
    ln -sfv "$dotfile" ~
  fi
done

# Make our bash_profile & bashrc the same file (OS X fail)
ln -fv ~/.bash_profile ~/.bashrc

vim +BundleInstall! +BundleClean! +qall
